import Head from 'next/head'
import Image from 'next/image'
import HeaderView from '../Components/Admin/HeaderView'
import Main from '../Components/Admin/Main'
import ShowStudentsHomeScreen from '../Components/Admin/ShowStudentsHomeScreen'
import CreateAdmin from '../Components/CreateAdmin'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Null Stress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
            <HeaderView />
            <CreateAdmin />
            <ShowStudentsHomeScreen></ShowStudentsHomeScreen>


          <div id="container2">
            <Main />
          </div>
       
      </main>

      <footer>Hei fra footer</footer>

    </div>
  )
}
